build:
    environment:
        php:
            version: 5.6, 7.0, 7.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
