build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
      environment:
        php:
          version: 8.3
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
    - 'docs/*'
    - '.github/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true