build:
  nodes:
    php73:
      environment:
        php: 7.3
    php74:
      environment:
        php: 7.4
    php80:
      environment:
        php: 8.0
    php81:
      environment:
        php: 8.1
    coverage:
      tests:
        override:
          - command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
            coverage:
              file: 'build/logs/clover.xml'
              format: 'clover'
